stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

test_backend:
  stage: test
  image: python:3.12

  script:
    - cd backend
    - pip install -r requirements.txt
    - python -m compileall app

build_backend:
  stage: build
  image: docker:27
  services:
    - docker:27-dind

  script:
    - docker build -t cloud-native-social-platform-backend ./backend

build_frontend:
  stage: build
  image: docker:27
  services:
    - docker:27-dind

  script:
    - docker build -t cloud-native-social-platform-frontend ./frontend